version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    command: "true"
    environment:
      - MPS_SSH_KEY_BASE64
      - MPS_REPO_URL
      - MPS_BRANCH_SOURCE
      - MPS_BRANCH_PUBLISH
