metrics:
  boolean:
    match:
      type: boolean
      labeled: false
  counter:
    match:
      type: counter
      labeled: false
  datetime:
    match:
      type: datetime
      labeled: false
  enumeration:
    match:
      type: enumeration
      labeled: false
  number:
    match:
      type: number
      labeled: false
  rate:
    match:
      type: rate
      labeled: false
  string:
    match:
      type: string
      labeled: false
  string_list:
    match:
      type: string_list
      labeled: false
  timespan:
    match:
      type: timespan
      labeled: false
  timing_distribution:
    match:
      type: timing_distribution
      labeled: false
  usage:
    match:
      type: usage
      labeled: false
  use_counter:
    match:
      type: use_counter
      labeled: false
  uuid:
    match:
      type: uuid
      labeled: false
  labeled_boolean:
    match:
      type: boolean
      labeled: true
  labeled_counter:
    match:
      type: counter
      labeled: true
  labeled_datetime:
    match:
      type: datetime
      labeled: true
  labeled_enumeration:
    match:
      type: enumeration
      labeled: true
  labeled_number:
    match:
      type: number
      labeled: true
  labeled_rate:
    match:
      type: rate
      labeled: true
  labeled_string:
    match:
      type: string
      labeled: true
  labeled_string_list:
    match:
      type: string_list
      labeled: true
  labeled_timespan:
    match:
      type: timespan
      labeled: true
  labeled_timing_distribution:
    match:
      type: timing_distribution
      labeled: true
  labeled_usage:
    match:
      type: usage
      labeled: true
  labeled_use_counter:
    match:
      type: use_counter
      labeled: true
  labeled_uuid:
    match:
      type: uuid
      labeled: true
